// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdHNokyUFtnZv2fCpm8Dqcypghe5xcWU',
    appId: '1:308725924911:web:fd5e4f1f0130de43fbb2da',
    messagingSenderId: '308725924911',
    projectId: 'fitness-tracker-b52f0',
    authDomain: 'fitness-tracker-b52f0.firebaseapp.com',
    databaseURL: 'https://fitness-tracker-b52f0-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-b52f0.firebasestorage.app',
    measurementId: 'G-K9XC89MK1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSA5SvzNln_vzpdAiKGS7rCfE_3s3kK4g',
    appId: '1:308725924911:android:dfddfd492860fc81fbb2da',
    messagingSenderId: '308725924911',
    projectId: 'fitness-tracker-b52f0',
    databaseURL: 'https://fitness-tracker-b52f0-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-b52f0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxXNzaGiEv0t5p3a2AcP7fTDUwoqJtxI',
    appId: '1:308725924911:ios:2da7f8997ebefdbbfbb2da',
    messagingSenderId: '308725924911',
    projectId: 'fitness-tracker-b52f0',
    databaseURL: 'https://fitness-tracker-b52f0-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-b52f0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxXNzaGiEv0t5p3a2AcP7fTDUwoqJtxI',
    appId: '1:308725924911:ios:2da7f8997ebefdbbfbb2da',
    messagingSenderId: '308725924911',
    projectId: 'fitness-tracker-b52f0',
    databaseURL: 'https://fitness-tracker-b52f0-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-b52f0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChdHNokyUFtnZv2fCpm8Dqcypghe5xcWU',
    appId: '1:308725924911:web:6d6b67d0aa25176dfbb2da',
    messagingSenderId: '308725924911',
    projectId: 'fitness-tracker-b52f0',
    authDomain: 'fitness-tracker-b52f0.firebaseapp.com',
    databaseURL: 'https://fitness-tracker-b52f0-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-b52f0.firebasestorage.app',
    measurementId: 'G-SMHG8SHKZG',
  );
}
