// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj3MBlqIvH23p3ISD5_h6BHonL59J0Pbk',
    appId: '1:699511959796:web:912a888a25d5beda616ea1',
    messagingSenderId: '699511959796',
    projectId: 'debug-practice',
    authDomain: 'debug-practice.firebaseapp.com',
    storageBucket: 'debug-practice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTy001EnIDpszYEYoGpE8_qqZamnilWAk',
    appId: '1:699511959796:android:04865de3fe0947db616ea1',
    messagingSenderId: '699511959796',
    projectId: 'debug-practice',
    storageBucket: 'debug-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5a-ueVBY43feGa-sie8mMAeZUpfig8c',
    appId: '1:699511959796:ios:b301a0b4ab5846fc616ea1',
    messagingSenderId: '699511959796',
    projectId: 'debug-practice',
    storageBucket: 'debug-practice.firebasestorage.app',
    iosBundleId: 'com.example.debugPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5a-ueVBY43feGa-sie8mMAeZUpfig8c',
    appId: '1:699511959796:ios:b301a0b4ab5846fc616ea1',
    messagingSenderId: '699511959796',
    projectId: 'debug-practice',
    storageBucket: 'debug-practice.firebasestorage.app',
    iosBundleId: 'com.example.debugPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj3MBlqIvH23p3ISD5_h6BHonL59J0Pbk',
    appId: '1:699511959796:web:8bc65a4ab5df8372616ea1',
    messagingSenderId: '699511959796',
    projectId: 'debug-practice',
    authDomain: 'debug-practice.firebaseapp.com',
    storageBucket: 'debug-practice.firebasestorage.app',
  );
}
