// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlijalcT7hAGpR89gnzf_hHfvSn3sjgJo',
    appId: '1:140029064852:web:00fd69d55fd7a01102e681',
    messagingSenderId: '140029064852',
    projectId: 'linkificproject1',
    authDomain: 'linkificproject1.firebaseapp.com',
    storageBucket: 'linkificproject1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNPB30E2FjNZzCbrd1CwkwkgE3bPg-pE',
    appId: '1:140029064852:android:8a8b1628194baf4d02e681',
    messagingSenderId: '140029064852',
    projectId: 'linkificproject1',
    storageBucket: 'linkificproject1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjluqdWkilAX_xnEqjjpWnJeusvGfdE0',
    appId: '1:140029064852:ios:01f7a82b4170a68202e681',
    messagingSenderId: '140029064852',
    projectId: 'linkificproject1',
    storageBucket: 'linkificproject1.firebasestorage.app',
    iosClientId: '140029064852-jn3p230ugfam5nqnr125k3mkqn33f9k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePractice',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjluqdWkilAX_xnEqjjpWnJeusvGfdE0',
    appId: '1:140029064852:ios:01f7a82b4170a68202e681',
    messagingSenderId: '140029064852',
    projectId: 'linkificproject1',
    storageBucket: 'linkificproject1.firebasestorage.app',
    iosClientId: '140029064852-jn3p230ugfam5nqnr125k3mkqn33f9k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlijalcT7hAGpR89gnzf_hHfvSn3sjgJo',
    appId: '1:140029064852:web:064a0f8517fe146502e681',
    messagingSenderId: '140029064852',
    projectId: 'linkificproject1',
    authDomain: 'linkificproject1.firebaseapp.com',
    storageBucket: 'linkificproject1.firebasestorage.app',
  );
}
